language: node_js
node_js:
  - 8.11.3
install:
  - npm install
  - sudo sh install-wine
before-script:
  - npm run lint
script:
  - npm run build-windows
  - (cd dist && zip -r -9 clipboard-manager-electron-win32-ia32.zip clipboard-manager-electron-win32-ia32)
  - npm run innosetup
deploy:
  provider: releases
  api_key:
    secure: jmMCDV4N7lKttde9j6LqT9V/OYRX11LWN8R18i04P+gm2p0JCFHfG1RcWAiT11wQo0ZWee7yZRDnJprkJWMUd4IIqloUPNUnqAVw+G0kNoPvz6n6EquDmvzWjvDjKfo3mowKy15GHwmFqfL1XQ4xLwI/1OeSpT0nEY3D6umElGV42dof4lYOPeto3WL+tfMkp/oyepb0Umgiqvoy5fLTt03pjBjcgud2v3fn6Ud+K3UM0JRM5k+SKPmC98+q+sfmVnl844FySJ2xYgiWbY8RR5mHKiLRKOP9mDCb0bFZ4qkTGF5BVV8ufY+5wdBCfZdLfpvVhHrEnzNjp1BjYqN8sBm+bkbxAoMTM2Heor3kHZANMASsvOtPPpePwxtAXHkK8Z1zXq8rXkCHziZdw4Xop0078rs/KgB8SkioGwTarAG4CLPRmDI/SJP0cCODy6QI4YUZijwpxr3186MleyXGSPV7a02qkSpgEieMZXAVCkWfflvvAz7jrZBw3IuQrrHn00u2inWdAUavBytpOc02luAKaFT5MiR9J3fC7ZwLXf8+ycFcrOq5oVQlRqlM4pLGW+YBBqhqV2ao58htT2NUrh4Z6CPAGamAxnjKlYCFYE/H7csIln6J8YuCXjQe4cJD7rysrrIh4fxQRdmTD/hslOoSCU33DwTDf9eSC5OjJ5o=
  file:
    - dist/clipboard-manager-electron-win32-ia32.zip
    - dist/setup-clipboard-manager-electron-win32-ia32.exe
  skip_cleanup: true
  on:
    repo: dotenorio/clipboard-manager-electron
    tags: true
